force-app/main/default/objects/nd_picklist__c/nd_picklist__c.object-meta.xml
<CustomObject>
    <label>nd picklist</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>nd picklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>nd picklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/nd_picklist__c/fields/active__c.field-meta.xml
<CustomField>
    <fullName>active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/nd_picklist__c/fields/code__c.field-meta.xml
<CustomField>
    <fullName>code__c</fullName>
    <label>code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/nd_picklist__c/fields/code_record_id__c.field-meta.xml
<CustomField>
    <fullName>code_record_id__c</fullName>
    <externalId>true</externalId>
    <label>code record id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/nd_picklist__c/fields/field_api_name__c.field-meta.xml
<CustomField>
    <fullName>field_api_name__c</fullName>
    <label>field api name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/nd_picklist__c/fields/namespace_prefix__c.field-meta.xml
<CustomField>
    <fullName>namespace_prefix__c</fullName>
    <label>namespace prefix</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/nd_picklist__c/fields/object_api_name__c.field-meta.xml
<CustomField>
    <fullName>object_api_name__c</fullName>
    <label>object api name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/nd_picklist__c/fields/unique_id__c.field-meta.xml
<CustomField>
    <fullName>unique_id__c</fullName>
    <externalId>true</externalId>
    <label>unique id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RecordtypeSyncBatch.cls
global  class RecordtypeSyncBatch  implements Database.Batchable<string>, Database.Stateful{
	global list<string> start(Database.BatchableContext bc) {
        set<string> objectList = new set<string>();
        for(RecordType rt : [SELECT ID, name, developername, sObjecttype, isActive, NamespacePrefix from recordtype ORDER BY SObjectType ASC]) {
            objectList.add(rt.sObjectType);
        }
        //system.debug('objectList '+objectList);
        return (Test.isRunningTest() ? new list<string>{new list<string>(objectList)[0]} : new list<string>(objectList));
    }
	global void execute(Database.BatchableContext bc, List<string> scope){ 
        list<nd_picklist__c> nd_picklist = new list<nd_picklist__c>();
        list<nd_picklist__c> nd_picklistDelete = new list<nd_picklist__c>();

		string objectName = scope[0];
        map<Id, recordType> rtMap = new map<Id, recordType>([SELECT ID, name, developername, sObjecttype, isActive, NamespacePrefix from recordtype where sObjecttype = :objectName]);
        
        //system.debug('rtMap '+rtMap);
        list<nd_picklist__c> exsitingRTs = [SELECt Id, code__c, description__c, code_record_id__c, active__c, field_api_name__c FROM  nd_picklist__c WHERE field_api_name__c = 'RecordTypeId' AND object_api_name__c = :objectName];
        map<Id, nd_picklist__c> existingRTMap = new map<Id, nd_picklist__c>();
        for(nd_picklist__c pl : exsitingRTs) {
            existingRTMap.put(pl.code_record_id__c, pl);
        }
        for(recordtype recs : rtMap.values()){
          nd_picklist__c ps = existingRTMap.containsKey(recs.Id) ? existingRTMap.get(recs.Id) : new nd_picklist__c();
            if(ps.code_record_id__c != null) {
                if(ps.code__c  != recs.developername || ps.description__c != recs.name || ps.active__c != recs.isActive) {
                	ps.code__c  = recs.developername;
                    ps.description__c = recs.name;
                    ps.active__c = recs.isActive;
                    nd_picklist.add(ps);
                }
            }
            else {
          ps.code_record_id__c =  recs.id;
          ps.namespace_prefix__c = recs.NamespacePrefix;
          ps.object_api_name__c = recs.sObjectType.toLowerCase();
          ps.field_api_name__c = 'RecordTypeId'.toLowerCase();
          ps.code__c  = recs.developername;
          ps.description__c = recs.name;
          ps.active__c = recs.isActive;
          ps.unique_id__c = recs.id;
          nd_picklist.add(ps);
            }
          /*  
          nd_recordtype_sync__c irs = new  nd_recordtype_sync__c();
          irs.recordtype_developer_name__c = recs.developername;
          irs.recordtype_id__c = recs.id;
          irs.recordtype_name__c = recs.name;
          irs.recordtype_object_api_name__c = recs.sObjectType;
          irs.active__c = recs.isActive;
          irs.namespace_prefix__c = recs.NamespacePrefix;
          rs.add(irs);  
        }
        upsert rs recordtype_id__c;*/
        }
        
        for(nd_picklist__c ndp : exsitingRTs) {
            if(!rtMap.containsKey(ndp.code_record_id__c)) {
                nd_picklistDelete.add(ndp);
            }
        }
        upsert nd_picklist code_record_id__c;
        
        if(nd_picklistDelete.size() > 0) {
            delete nd_picklistDelete;
        }
    }
    global void finish(Database.BatchableContext bc){
       
    }
}