force-app/main/default/objects/Lottery_Application__c/Lottery_Application__c.object-meta.xml
<CustomObject>
    <label>Lottery Application</label>
    <nameField>
        <displayFormat>LA-{0}</displayFormat>
        <label>Lottery Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lottery Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lottery_Application__c/fields/Apply_Proposed_Lottery_Application__c.field-meta.xml
<CustomField>
    <fullName>Apply_Proposed_Lottery_Application__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For use with Lottery Reporting TASK0198615. This checkbox applies the &quot;Proposed Lottery Application Level&quot; to the donors actual &quot;Lottery Application Level&quot;. When saving this record with this field checked, automation will trigger that change as well as a few other tasks such as saving off the previous app to field &quot;Replaced Lottery Application Level&quot;.</description>
    <inlineHelpText>This checkbox applies the &quot;Proposed Lottery Application Level&quot; to the donors actual &quot;Lottery Application Level&quot;. When saving this record with this field checked, automation will trigger that change as well as a few other tasks such as saving off the previous app to field &quot;Replaced Lottery Application Level&quot;.</inlineHelpText>
    <label>Apply Proposed Lottery Application</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/Earned_Application_Audit__c.field-meta.xml
<CustomField>
    <fullName>Earned_Application_Audit__c</fullName>
    <inlineHelpText>Detailed calculation for field &quot;Lottery Application Level&quot;</inlineHelpText>
    <label>Current Earned Application Audit</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/locked_for_automated_updates__c.field-meta.xml
<CustomField>
    <fullName>locked_for_automated_updates__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Locked/Unlocked for further automated process updates. Locked means no automated process should change this application, but users can still make changes.</description>
    <inlineHelpText>Locked/Unlocked for further automated process updates. Locked means no automated process should change this application, but users can still make changes.</inlineHelpText>
    <label>Lock</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/Lottery_Application_Level__c.field-meta.xml
<CustomField>
    <fullName>Lottery_Application_Level__c</fullName>
    <label>Lottery Application Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lottery_Application_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/Proposed_Earned_Application_Audit__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Earned_Application_Audit__c</fullName>
    <description>For use with Lottery Reporting TASK0198615. This is the detail on how the field &quot;Proposed Lottery Application Level&quot; was calculated.</description>
    <inlineHelpText>This is the detail on how the field &quot;Proposed Lottery Application Level&quot; was calculated.</inlineHelpText>
    <label>Proposed Earned Application Audit</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/Proposed_Lottery_Application_Level__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Lottery_Application_Level__c</fullName>
    <description>For use with Lottery Reporting TASK0198615. This is the application level calculated by the system. It is possible this does not match their currently assigned app in field &quot;Lottery Application Level&quot; because it has not been reviewed yet. During some times of the year, calculated applications are not automatically applied to a donor&apos;s final application level due to requiring a review first.</description>
    <inlineHelpText>This is the application level calculated by the system. It is possible this does not match their currently assigned app in field &quot;Lottery Application Level&quot; because it has not been reviewed yet. During some times of the year, calculated applications are not automatically applied to a donor&apos;s final application level due to requiring a review first.</inlineHelpText>
    <label>Proposed Lottery Application Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lottery_Application_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/Replaced_Lottery_Application_Level__c.field-meta.xml
<CustomField>
    <fullName>Replaced_Lottery_Application_Level__c</fullName>
    <description>For use with Lottery Reporting TASK0198615</description>
    <label>Replaced Lottery Application Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lottery_Application_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lottery_Application__c/fields/Replaced_Lottery_Application_Level_Audit__c.field-meta.xml
<CustomField>
    <fullName>Replaced_Lottery_Application_Level_Audit__c</fullName>
    <description>For use with Lottery Reporting TASK0198615. WWhen a Proposed Lottery Application is moved to the main &quot;Lottery Application Level&quot; Field, the old Lottery Application Audit will be moved here to help track why the app changed.</description>
    <inlineHelpText>When a Proposed Lottery Application is moved to the main &quot;Lottery Application Level&quot; Field, the old Lottery Application Audit will be moved here to help track why the app changed.</inlineHelpText>
    <label>Replaced Lottery Application Level Audit</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/nd_fb_apply_proposed_trigger_handler.cls
global class nd_fb_apply_proposed_trigger_handler extends ucinn_ascendv2.ascend_TDTM_Runnable
{
    private ucinn_ascendv2.ascend_TDTM_Runnable.DmlWrapper dmlWrapper = new ucinn_ascendv2.ascend_TDTM_Runnable.DmlWrapper();

    global override ucinn_ascendv2.ascend_TDTM_Runnable.DmlWrapper run(List<SObject> newList, List<SObject> oldList, ucinn_ascendv2.ascend_TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult)
    {
        List<Lottery_Application__c> triggerNew = (List<Lottery_Application__c>) newList;
        List<Lottery_Application__c> triggerOld = (List<Lottery_Application__c>) oldList;
        
        Map<Id, Lottery_Application__c> triggerOldMap = new Map<Id, Lottery_Application__c>();
        if (triggerOld != null)
        {
            for (Lottery_Application__c old : triggerOld)
            {
                triggerOldMap.put(old.Id, old);
            }
        }

    for(Lottery_Application__c app : triggerNew)
    {
        if ( !app.locked_for_automated_updates__c )
        {
            if ( trigger.isUpdate )
            {
                // only apply changes if the proposed app is different from the current app
                if ( app.Apply_Proposed_Lottery_Application__c  && app.Proposed_Lottery_Application_Level__c != triggerOldMap.get(app.Id)?.Lottery_Application_Level__c )
                {
                    app.Replaced_Lottery_Application_Level__c = triggerOldMap.get(app.Id)?.Lottery_Application_Level__c;
                    app.Replaced_Lottery_Application_Level_Audit__c = triggerOldMap.get(app.Id)?.Earned_Application_Audit__c;
                    app.Lottery_Application_Level__c = app.Proposed_Lottery_Application_Level__c;
                    app.Earned_Application_Audit__c = app.Proposed_Earned_Application_Audit__c;
                }
            }
    
            if ( trigger.isInsert )
            {
                // only apply changes if the proposed app is different from the current app
                if ( app.Apply_Proposed_Lottery_Application__c && app.Proposed_Lottery_Application_Level__c != app.Lottery_Application_Level__c )
                {
                    app.Replaced_Lottery_Application_Level__c = app.Lottery_Application_Level__c;
                    app.Replaced_Lottery_Application_Level_Audit__c = app.Earned_Application_Audit__c;
                    app.Lottery_Application_Level__c = app.Proposed_Lottery_Application_Level__c;
                    app.Earned_Application_Audit__c = app.Proposed_Earned_Application_Audit__c;
                }
            }
        }

        // this should always go back to false since it is our trigger to apply the next change
        app.Apply_Proposed_Lottery_Application__c = false;
    }
       
        return dmlWrapper;
    }
    
}