force-app/main/default/objects/Beat_Alert_Setting__mdt/Beat_Alert_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Beat Alert Setting</label>
    <pluralLabel>Beat Alert Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Beat_Alert_Setting__mdt/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/nd_Announcements__c/nd_Announcements__c.object-meta.xml
<CustomObject>
    <description>Used for UR News</description>
    <label>Announcement</label>
    <nameField>
        <displayFormat>AN-{0000000000}</displayFormat>
        <label>Announcements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/nd_Announcements__c/fields/nd_Message__c.field-meta.xml
<CustomField>
    <fullName>nd_Message__c</fullName>
    <label>Message</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/nd_Announcements__c/fields/nd_Order__c.field-meta.xml
<CustomField>
    <fullName>nd_Order__c</fullName>
    <description>Used for ordering records on the display.</description>
    <inlineHelpText>Used for ordering records on the display.</inlineHelpText>
    <label>Order</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/nd_Announcements__c/fields/nd_Status__c.field-meta.xml
<CustomField>
    <fullName>nd_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/nd_Announcements__c/fields/nd_Subject__c.field-meta.xml
<CustomField>
    <fullName>nd_Subject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnnouncementController.cls
public class AnnouncementController {

    @AuraEnabled(cacheable=true)
    public static List<nd_Announcements__c> getAnnouncements(){
        try {
            return [SELECT id,nd_Subject__c, Name, nd_Message__c FROM nd_Announcements__c WHERE nd_Status__c = 'Active' ORDER BY nd_Order__c ASC];
        } catch (Exception e) {throw new AuraHandledException(e.getMessage());}
    }

    @AuraEnabled(cacheable=true)
    public static Beat_Alert_Setting__mdt getCMT(){

            return [SELECT id, Link__c FROM Beat_Alert_Setting__mdt WHERE DeveloperName = 'Announcement_Files_and_Guidelines' LIMIT 1];
        
    }

}