force-app/main/default/objects/BEAT_Alert__c/BEAT_Alert__c.object-meta.xml
<CustomObject>
    <label>BEAT Alert</label>
    <nameField>
        <displayFormat>BA-{0000000000}</displayFormat>
        <label>BEAT Alerts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BEAT Alerts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BEAT_Alert__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Campaign.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>BEAT_Event</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>BEAT Alerts</relationshipLabel>
    <relationshipName>BEAT_Alerts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BEAT_Alert__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>5000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/BEAT_Alert__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Used for ordering records on the display.</description>
    <inlineHelpText>Used for ordering records on the display.</inlineHelpText>
    <label>Order</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Beat_Alert_Setting__mdt/Beat_Alert_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Beat Alert Setting</label>
    <pluralLabel>Beat Alert Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Beat_Alert_Setting__mdt/fields/Link__c.field-meta.xml
<CustomField>
    <fullName>Link__c</fullName>
    <label>Link</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/BeatEventAlertController.cls
public with sharing class BeatEventAlertController {
    @AuraEnabled(cacheable=true)
    public static List<BEAT_Alert__c> getBeatAlerts(){
        try {
            return [SELECT id, Event__c, Event__r.Name, Message__c FROM BEAT_Alert__c WHERE Status__c = 'Active' ORDER BY Order__c ASC];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Beat_Alert_Setting__mdt getCMT(){
        try {
            return [SELECT id, Link__c FROM Beat_Alert_Setting__mdt WHERE DeveloperName = 'Beat_Alert_Guidelines' LIMIT 1];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}