force-app/main/default/objects/Wealth_Asset__c/Wealth_Asset__c.object-meta.xml
<CustomObject>
    <label>Wealth Asset</label>
    <nameField>
        <label>Wealth Assets Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wealth Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wealth_Asset__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company Valuation</fullName>
            </value>
            <value>
                <fullName>Luxury Items</fullName>
            </value>
            <value>
                <fullName>Real Estate</fullName>
            </value>
            <value>
                <fullName>Salary Estimate</fullName>
            </value>
            <value>
                <fullName>Stock/Options</fullName>
            </value>
            <value>
                <fullName>Foundation Assets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Wealth_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Unverified</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Wealth_Asset__c/fields/Value_Evaluation_Date__c.field-meta.xml
<CustomField>
    <fullName>Value_Evaluation_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Value Evaluation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TRIG_Wealth_AssetTest.cls
@isTest(SeeAllData=false)
private class TRIG_Wealth_AssetTest {

    @isTest(SeeAllData=false) 
    static void insertAR() {
       
        Test.startTest();
        Wealth_Asset__c new_ar = new Wealth_Asset__c();

        new_ar.name	 = 'Company Valuation';
        new_ar.Category__c ='Company Valuation';
        new_ar.Status__c = 'Active';
        new_ar.Value_Evaluation_Date__c = system.today();
        insert new_ar;
        Test.stopTest();

        
        Wealth_Asset__c s01 = [SELECT Id, Category__c FROM Wealth_Asset__c where name	 = 'Company Valuation'  LIMIT 1];
        System.assertEquals('Company Valuation', s01.Category__c);
    }
}