force-app/main/default/objects/Integration_Out__c/Integration_Out__c.object-meta.xml
<CustomObject>
    <description>integration_out</description>
    <label>Integration Out</label>
    <nameField>
        <label>Integration Out Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Outs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Out__c/fields/Date_Modified__c.field-meta.xml
<CustomField>
    <fullName>Date_Modified__c</fullName>
    <description>date of insert update delete (pull this from the date modified on the record ideally)</description>
    <label>Date Modified</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Integration_Out__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>I/U/D - (for insert update delete)</description>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Out__c/fields/json_message__c.field-meta.xml
<CustomField>
    <fullName>json_message__c</fullName>
    <label>json message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Out__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>place to put an error message</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Out__c/fields/Modified_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Modified_Record_Id__c</fullName>
    <label>Modified Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Out__c/fields/Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Api_Name__c</fullName>
    <description>api name of salesforce object that was inserted/updated/deleted</description>
    <label>Object Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Out__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>(N,E,P,X) for New/Error/successfully Processed/Ignore</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Ready</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationProducerBatchTest.cls
@isTest(SeeAllData=false)
public class IntegrationProducerBatchTest {

    
     @testSetup 
    static void setup() {
		/** The code in this section will create test records only once
		 *  The test data can then be used by multiple test methods in
		 *  this test class
		 */
		Account a = new Account(name='Sirius Satellite');
        Account a2 = new Account(name='EMPLOYER IN NAME ONLY');
        insert new List<Account>{a, a2};
        //Account newOrganization = [select id from Account where name = 'Sirius Satellite' limit 1];
         
        Contact c = new Contact(accountid = a.Id, firstname = 'Sarah', lastname = 'Farris', Email='sfarris@ttech.edu', Constituent_Status__c='A');
        Contact c2 = new Contact(accountid = a2.Id, firstname = 'Dan', lastname = 'Lebatard', Email='lebatard@espn.com', Constituent_Status__c='A' );
        insert new List<Contact>{c, c2};
        //insert c;  
        
    }
    static testmethod void testContact() {
        
        Contact newConstituent = [select id from contact where name='Sarah Farris' limit 1];
        Account newOrganization = [select id from Account where name = 'Sirius Satellite' limit 1];
        //List<Integration_Out__c> intList= new List<Integration_Out__c>();
         datetime today = system.now();
        Integration_Out__c intOut = new Integration_Out__c(Name = newConstituent.Id, Modified_Record_Id__c = newConstituent.Id, event_type__c='I', Object_Api_Name__c='Contact', Status__c = 'N', Date_Modified__c=today);
        insert intOut;
        
        
        Test.startTest();
        // CRON expression: midnight on March 15. Because this is a test, 
    	// job is supposed to execute immediately after Test.stopTest()
    	/*
        String cronExpr = '0 0 0 15 3 ? 2022';
		IntegrationProducerBatchScheduler abs= new IntegrationProducerBatchScheduler();
		String jobId = System.schedule('IntegrationProducerBatchTest', cronExpr, abs);
		abs.execute(null);
        */
        Database.executeBatch(new IntegrationProducerBatch(false), 200);
		Test.stopTest();
        
        Integration_Out__c[] ints = [select id, name, Modified_Record_Id__c, json_message__c, event_type__c, status__c, Message__c from Integration_Out__c where Modified_Record_Id__c = :newConstituent.Id];
        system.debug('json message: ' + ints[0].json_message__c);
        
         Map<String, Object> m =(Map<String, Object>) JSON.deserializeUntyped(ints[0].json_message__c);
         Map<String, Object> newMap = (Map<String, Object>) m.get('object');
         Map<String, Object> newEvent = (Map<String, Object>) newmap.get('event');
         Map<String, Object> newtarget = (Map<String, Object>) newmap.get('target');
        //system.debug('testContact newtarget: '+newtarget);

        
        System.assertEquals('Sarah Farris', newtarget.get('Name'));
        System.assertEquals(newOrganization.id, newtarget.get('AccountId'));
        

        system.assert(ints[0].status__c == 'R'); 
        //system.assert(c. == 'R'); 
   
    }
    static testmethod void testDelete() {
        Contact newConstituent = [select id from contact where name='Sarah Farris' limit 1];
        Id conId = newConstituent.id;
        List<Contact> deleteList = new List<Contact>();
        deleteList.add(newConstituent);
        delete deleteList;
        
        
        datetime today = system.now();
        Integration_Out__c intOut = new Integration_Out__c(Name = conId, Modified_Record_Id__c = conId, event_type__c='U', Object_Api_Name__c='Contact', Status__c = 'N', Date_Modified__c=today);
        insert intOut;
        
        
        Test.startTest();
        // CRON expression: midnight on March 15. Because this is a test, 
    	// job is supposed to execute immediately after Test.stopTest()
    	/*
        String cronExpr = '0 0 0 15 3 ? 2022';
		IntegrationProducerBatchScheduler abs= new IntegrationProducerBatchScheduler();
		String jobId = System.schedule('IntegrationProducerBatchTest', cronExpr, abs);
		abs.execute(null);*/
        Database.executeBatch(new IntegrationProducerBatch(false), 200);
        
		Test.stopTest();
        
        Integration_Out__c[] ints = [select id, name, Modified_Record_Id__c, json_message__c, event_type__c, status__c, Message__c from Integration_Out__c where Modified_Record_Id__c = :conId];
        system.assert(ints[0].event_type__c == 'D'); 
        system.assert(ints[0].status__c == 'R'); 
        
        Map<String, Object> m =(Map<String, Object>) JSON.deserializeUntyped(ints[0].json_message__c);
         Map<String, Object> newMap = (Map<String, Object>) m.get('object');
         Map<String, Object> newEvent = (Map<String, Object>) newmap.get('event');
         Map<String, Object> newtarget = (Map<String, Object>) newmap.get('target');
        
        System.assert(newtarget.isEmpty());
        
        
        
        
    }
    
}